services:
  postgres:
    image: postgres:16
    container_name: loan-postgres
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_password
    ports:
      - "5433:5432"
    volumes:
      - loan-postgres-data:/var/lib/postgresql/data

volumes:
  loan-postgres-data: